<template>
    <v-container class="page-text" style="min-height: 100vh">
        <v-col>
            <v-row>
                <h1 class="text-h4">About this site</h1>
                <p class="text-body-1">
                    This is an interactive map tool developed to allow users to access and explore high resolution
                    dengue transmission intensity in countries where dengue is endemic. These maps were generated by
                    fitting environmentally driven geospatial models to force of infection estimates derived from
                    surveillance data including case-notification data and cross-sectional serological surveys. We
                    provide estimates of:
                </p>
                <ul class="text-body-1">
                    <li>
                        The average dengue force of infection (i.e. the per capita annual risk of dengue infection for a
                        susceptible individual)
                    </li>
                    <li>The seroprevalence at 9 years of age</li>
                    <li>The annual expected number of hospital admissions by age</li>
                </ul>
                <p class="text-body-1">
                    Estimates of these metrics are available at the first and second administrative unit level.
                </p>
                <!-- <p class="text-body-1">We gratefully acknowledge support for this work from XXX.</p> -->
            </v-row>
            <v-row class="justify-center mt-12">
                <v-img
                    alt="Logo of the Jameel Institute"
                    src="@/assets/ICL_Jameel_Full-Lock-up_RGB Transparent.png"
                    max-height="100px"
                    max-width="50vw"
                />
            </v-row>
            <v-row class="justify-center">
                <v-img
                    alt="Logo of Imperial College London"
                    src="@/assets/Imperial logo new - BLUE transparent.png"
                    max-height="200px"
                    max-width="50vw"
                />
            </v-row>
            <v-row class="justify-center">
                <v-img
                    alt="Logo of the MRC Centre for Global Infectious Disease Analysis (MRC GIDA)"
                    src="@/assets/MRC GIDA logo.png"
                    max-height="80px"
                    max-width="50vw"
                />
                <!-- Placeholder for DNDI logo (Ilaria to check if we should use it) -->
                <!-- Placeholder for WHO logo (WHO to provide) -->
            </v-row>
        </v-col>
    </v-container>
</template>
