<template>
    <v-container class="page-text" style="min-height: 100dvh">
        <v-col>
            <v-row>
                <h1 class="text-h4">About this site</h1>
                <p class="text-body-1">
                    This is an interactive map tool developed to allow users to access and explore high resolution
                    dengue transmission intensity in countries where dengue is endemic. These maps were generated by
                    fitting environmentally driven geospatial models to force of infection estimates derived from
                    surveillance data including case-notification data and cross-sectional serological surveys. Full
                    details of the methods used to generate these estimates are provided in Cattarino et al. [1].
                </p>
                <p class="text-body-1">We provide estimates of:</p>
            </v-row>
            <v-row>
                <ul class="text-body-1">
                    <li>
                        The average dengue force of infection (i.e. the per capita annual risk of dengue infection for a
                        susceptible individual)
                    </li>
                    <li>The seroprevalence at 9 years of age</li>
                    <li>The annual expected number of hospital admissions by age</li>
                </ul>
                <p class="text-body-1">
                    Estimates of these metrics are available at the first and second administrative unit level.
                </p>
                <p class="text-body-1">
                    We acknowledge research funding from the MRC Centre for Global Infectious Disease Analysis
                    (reference MR/X020258/1), funded by the UK Medical Research Council (carried out in the frame of the
                    Global Health EDCTP3 Joint Undertaking) and also from Community Jameel and Wellcome Trust. The tool
                    was co-funded by the World Health Organization and developed in collaboration with the Drugs for
                    Neglected Diseases initiative.
                </p>
                <p>
                    You are viewing {{ appConfig?.title }} version {{ PACKAGE_VERSION }}.
                    <v-btn
                        variant="plain"
                        size="small"
                        :ripple="false"
                        class=""
                        @click="showVersionDetails = !showVersionDetails"
                    >
                        {{ showVersionDetails ? "Hide" : "Show" }} details
                    </v-btn>
                </p>
            </v-row>
            <v-row>
                <div v-if="showVersionDetails" class="text-body-1">
                    Git branch: {{ GIT_BRANCH }} | Git commit: {{ GIT_COMMIT }}
                </div>
            </v-row>
            <v-row>
                <p class="text-body-1 font-italic">
                    [1] L. Cattarino, I. Rodriguez-Barraquer, N. Imai, D. A. T. Cummings, and N. M. Ferguson, “Mapping
                    global variation in dengue transmission intensity,” Sci. Transl. Med., vol. 12, no. 528, Jan. 2020.
                </p>
            </v-row>
            <v-row> </v-row>
            <v-row class="justify-center mt-12">
                <v-img
                    alt="Logo of the Drugs for Neglected Diseases initiative (DNDi)"
                    src="@/assets/DNDi_Logo_EN_Full Colour_margins.png"
                    max-height="150px"
                />
            </v-row>
            <v-row class="justify-center">
                <v-img
                    alt="Logo of the Jameel Institute"
                    src="@/assets/ICL_Jameel_Full-Lock-up_RGB Transparent.png"
                    max-height="100px"
                />
            </v-row>
            <v-row class="justify-center">
                <v-img
                    alt="Logo of Imperial College London"
                    src="@/assets/Imperial logo new - BLUE transparent.png"
                    max-height="170px"
                />
            </v-row>
            <v-row class="justify-center">
                <v-img
                    alt="Logo of the MRC Centre for Global Infectious Disease Analysis (MRC GIDA)"
                    src="@/assets/MRC GIDA logo.png"
                    max-height="80px"
                />
            </v-row>
        </v-col>
    </v-container>
</template>
<script setup>
import { storeToRefs } from "pinia";
import { GIT_BRANCH, GIT_COMMIT, PACKAGE_VERSION } from "../version";
import { useAppStore } from "../stores/appStore";

const { appConfig } = storeToRefs(useAppStore());

const showVersionDetails = ref(false);
</script>
